# Modifying metadata.annotations does not trigger a rolling update.
# You need to modify spec.template.metadata.annotations, which is part of the Pod template,
# and Kubernetes uses it to decide whether to perform a rolling update.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: als
  annotations:
    build: "20250830_164003"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        build: "20250830_164003"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: node
          image: node:20.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-auth-secret
                  key: AUTH_SECRET
          command:
            - sh
            - -c
            - |
              set -e
              git clone https://github.com/wsva/als_next.js_build /home/node/app
              cd /home/node/app
              echo 'DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/alsdb' > .env
              echo 'NEXTAUTH_URL=https://yanansworkshop.site' >> .env
              echo 'AUTH_SECRET="${AUTH_SECRET}"' >> .env
              echo 'AUTH_TRUST_HOST=true' >> .env
              echo 'OAUTH2_AUTHORIZATION=https://yanansworkshop.site/oauth2/authorize' >> .env
              echo 'OAUTH2_TOKEN=https://yanansworkshop.site/oauth2/token' >> .env
              echo 'OAUTH2_USERINFO=https://yanansworkshop.site/oauth2/userinfo' >> .env
              echo 'OAUTH2_CLIENT_ID=als_next.js' >> .env
              node server.js
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: als
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
    - port: 3000
      targetPort: 3000